# Generated by Django 4.2.3 on 2023-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mascot', models.CharField(max_length=50)),
                ('head_of_house', models.CharField(max_length=50)),
                ('house_ghost', models.CharField(max_length=50)),
                ('founder', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
            ],
        ),
    ]
